# Generated by Django 5.1 on 2024-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('Plan_Type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=10)),
                ('price_id', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
