# Generated by Django 5.1 on 2024-10-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_rename_plan_duration_plan_plan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_id',
            field=models.CharField(default='Add product id here', max_length=20),
        ),
    ]
