# Generated by Django 5.1 on 2024-11-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_plan_plan_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
